// src/components/TechStack.tsx
'use client'

import { useI18n } from '@/i18n/LocaleProvider'
import Reveal from './Reveal'

const TECHNOLOGIES = [
  { name: 'Vue', icon: 'vuejs' },
  { name: 'React', icon: 'react' },
  { name: 'Node.js', icon: 'nodejs' },
  { name: 'Python', icon: 'python' },
  { name: 'TypeScript', icon: 'typescript' },
  { name: 'Git', icon: 'git' },
] as const

export default function TechStack() {
  const { t } = useI18n()

  return (
    <section className="px-6 py-20">
      <div className="mx-auto max-w-4xl">
        <Reveal>
          <h2 className="text-center text-3xl font-semibold tracking-tight text-ink sm:text-4xl">
            {t('home.techStack.title')}
          </h2>
        </Reveal>
        <div className="mt-10 grid grid-cols-3 gap-4 sm:grid-cols-6">
          {TECHNOLOGIES.map((tech, i) => (
            <Reveal key={tech.name} delay={i * 50}>
              <div className="glass-card flex flex-col items-center p-5">
                <img
                  src={`https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${tech.icon}/${tech.icon}-original.svg`}
                  alt={tech.name}
                  width={40}
                  height={40}
                  loading="lazy"
                  className="h-10 w-10"
                />
                <span className="mt-2 text-xs font-medium text-muted">
                  {tech.name}
                </span>
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  )
}

// src/components/TechStack.vue
<script setup>
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const technologies = [
  { name: 'Vue', icon: 'vue' },
  { name: 'React', icon: 'react' },
  { name: 'Node.js', icon: 'nodejs' },
  { name: 'Python', icon: 'python' },
  { name: 'TypeScript', icon: 'typescript' },
  { name: 'Git', icon: 'git' },
]
</script>

<template>
  <section class="py-16 px-4">
    <h2 class="text-2xl font-bold text-center text-gray-900 mb-8">{{ t('home.techStack.title') }}</h2>
    <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4 max-w-4xl mx-auto">
      <div
        v-for="tech in technologies"
        :key="tech.name"
        class="flex flex-col items-center p-4 bg-white rounded-xl shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all"
      >
        <div class="w-12 h-12 flex items-center justify-center mb-2">
          <img
            :src="`https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${tech.icon}/${tech.icon}-original.svg`"
            :alt="tech.name"
            class="w-10 h-10"
            loading="lazy"
          />
        </div>
        <span class="text-sm font-medium text-gray-700">{{ tech.name }}</span>
      </div>
    </div>
  </section>
</template>
